FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
RUN npm install -g dotenv-cli
COPY package*.json .
RUN npm install
COPY --from=build /app/dist ./dist
ENV PORT=4000
ENV CORS_ORIGIN=*
EXPOSE 4000
CMD ["node", "dist/index.js"]
